spring.main.web-application-type: NONE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boddari
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    joyyir.boddari: INFO
    root: WARN
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG

constant:
  upbit:
    access-key: 3dx505OKm6I1AaAo8Eu0LSVORa1HJyxd3M0JKZc9
    secret-key: xxuJtNxIOYPFopvyqfiRMfn2xek4WpT6RJHmmRF0
  huobi:
    access-key: a8a59575-uymylwhfeg-82263b6d-32376
    secret-key: e0ef1efa-a9370669-b200c1d2-1a599
  binance:
    access-key: EDwgbfQ2ZZaRbi3w7pLmvtoRvgy83EeSf3M5VBmfbX7iix6zCTsd4Iz4o30HEpHk
    secret-key: 1uuFIiztcBvM18U83xcDvgq0art62Nm6UmhoRHo9xEm5IP7HMUyk1iZPsmnXpyzc
  telegram-boddaribot:
    access-token: 1633252158:AAE5FoLmKzqNcIswoOU202RDC49ytC-RrmE
    chat-id: 1080798457