spring.main.web-application-type: NONE

spring:
  datasource:
    url: jdbc:mysql://your-mysql-url
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    joyyir.boddari: INFO
    root: WARN
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG

constant:
  telegram-boddaribot:
    access-token: your-access-token
  grafana:
    api-key: your-api-key
  graph-image-path: /your/graph/image/path
  graph-url: http://your-graph-url