spring.main.web-application-type: NONE

spring:
  datasource:
    url: jdbc:mysql://your-mysql-url
    username: your-username
    password: your-password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    joyyir.boddari: INFO
    root: WARN
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#    org.apache.http: DEBUG
#    httpclient.wire: DEBUG

constant:
  upbit:
    access-key: your-access-key
    secret-key: your-secret-key
  binance:
    access-key: your-access-key
    secret-key: your-secret-key
  telegram-boddaribot:
    access-token: your-access-token
